openapi: 3.0.2
info:
  version: 0.1.0
  title: LinkMink
  termsOfService: 'api.linkmink.com/terms'
  contact:
    email: hello@linkmink.com
  # license:
  #   name: Apache 2.0
  #   url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  x-logo:
    url: 'https://redocly.github.io/openapi-template/logo.png'
  description: >
    This is an internal-only api specification for LinkMink developers. Some of the
    features of this api are not meant for public use.

    # Introduction

    The linkmink api provides LinkMink developers the specifications for REST endpoints
    that can be used to build features. This api is not rate limited and some of the 
    requests can return results that are quite large. For this reason it should not be
    used by any of LinkMink's customers.

tags:
  - name: Commissions
    description: Endpoints for working with commissions
  - name: User
    description: Operations about user
servers:
  - url: 'http://app.linkmink.com/api/v0.1.0'
paths:
  '/users/{username}':
    $ref: 'paths/users@{username}.yaml'
  /commissions:
    $ref: paths/commissions.yaml
  /commissions/metrics:
    $ref: paths/commissions@metrics.yaml
  /conversions:
    $ref: paths/conversions.yaml
  /conversions/metrics:
    $ref: paths/conversions@metrics.yaml
components:
  securitySchemes:
    api_key:
      type: http
      scheme: bearer
    basic_auth:
      type: http
      scheme: basic

security:
  - api_key: []